AWSTemplateFormatVersion: "2010-09-09"
Description: A sample template to mount efs to amazon instance in us-east-1
Parameters:
  VPC:
    Description: Vpc Id
    Type: AWS::EC2::VPC::Id
    Default:  "vpc-id"
Resources:
  MyEC2Instance:
    Type: "AWS::EC2::Instance"
    DependsOn: MountTarget
    Properties:
      ImageId: "ami-55ef662f"
      InstanceType: t2.micro
      KeyName: keyes
      IamInstanceProfile: !Ref InstanceProfile
      NetworkInterfaces:
      - NetworkInterfaceId: !Ref 'Eth0'
        DeviceIndex: '0'
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe
          sudo yum update -y
          sudo yum install -y nfs-utils
          sudo mkdir efs
          sudo mount -t nfs4 -o nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2 ${FileSystemEFS}.efs.${AWS::Region}.amazonaws.com:/ ~/efs
          cd ~/efs
          echo "${FileSystemEFS}.efs.${AWS::Region}.amazonaws.com" > test.txt

  Eth0:
    Type: AWS::EC2::NetworkInterface
    Properties:
      Description: eth0
      GroupSet: [!Ref 'InstanceSecurityGroup']
      SubnetId: 'subnet-id'

  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow http to client host
      VpcId: !Ref VPC
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 2049
        ToPort: 2049
        CidrIp: 0.0.0.0/0

  FileSystemEFS:
    Type: AWS::EFS::FileSystem
    Properties:
      FileSystemTags:
        - Key: Name
          Value: EFS1
      PerformanceMode: generalPurpose

  MountTarget:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref FileSystemEFS
      SubnetId: "subnet-id"
      SecurityGroups:
        - Ref: SecurityGroup

  RootRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action: ["sts:AssumeRole"]
            Principal:
              Service:
                - "ec2.amazonaws.com"
      Path: "/"
      Policies:
      - PolicyDocument:
          Statement:
            - Effect: "Allow"
              Action: "*"
              Resource : "*"
          Version: '2012-10-17'
        PolicyName: root

  InstanceProfile:
    Type: "AWS::IAM::InstanceProfile"
    Properties:
      Path: "/"
      Roles:
        -
          Ref: "RootRole"

  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access via port 22
      VpcId: !Ref VPC
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 443
        ToPort: 443
        CidrIp: 0.0.0.0/0
